version: "2"

volumes:
  givit-sync:
    external: true
  gem_store_240:
    external: true

services:
  web:
    build:
      context: .
      #dockerfile: docker/Dockerfile-web-dev
    command: ./start.sh
    #env_file: .env
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - gem_store_240:/gems
      - .:/givit
      - givit-sync:/givit:nocopy
