version: "2"

volumes:
  gem_store_240:
    external: true

networks:
  givit:

services:
  postgres:
    image: postgres:latest
    networks:
      - givit
    ports:
      - "5439:5432"
  web:
    #image: web:ruby
    build:
      context: .
    command: bash
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - "${LOCAL_PORT}:3000"
    volumes:
      - gem_store_240:/gems
      - .:/givit
    networks:
      - givit
