version: "2"

volumes:
  givit-sync:
    external: true
  gem_store_240:
    external: true

services:
  web:
    #image: web:ruby
    build:
      context: .
    command: ./start.sh
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - "${LOCAL_PORT}:3000"
    volumes:
      - gem_store_240:/gems
      - .:/givit
      - givit-sync:/givit:nocopy
