# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>

development:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>

test:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL_TEST"] %>